// modal
const UPDATE_MODAL_INFO = 'UPDATE_MODAL_INFO';
// events
const SAVE_EVENT = 'SAVE_EVENT';
const EDIT_EVENT = 'EDIT_EVENT';
const DELETE_EVENT = 'DELETE_EVENT';
const DELETE_ALL_DAY_EVENTS = 'DELETE_ALL_DAY_EVENTS';
const UPDATE_DATE_TIME_EVENT = 'UPDATE_DATE_TIME_EVENT';

export default {
  UPDATE_MODAL_INFO,
  SAVE_EVENT,
  EDIT_EVENT,
  UPDATE_DATE_TIME_EVENT,
  DELETE_EVENT,
  DELETE_ALL_DAY_EVENTS,
}
